// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV7gNrMOxcWkR_NlJGJq-GE5zOiXgo-rM',
    appId: '1:1036782783280:web:0245e437d491e1c75016f5',
    messagingSenderId: '1036782783280',
    projectId: 'yourvideocallvideo',
    authDomain: 'yourvideocallvideo.firebaseapp.com',
    storageBucket: 'yourvideocallvideo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmlp69S2M6SPuJ_kKxHSpPasDaIw1Do58',
    appId: '1:1036782783280:android:ed75905df02acf505016f5',
    messagingSenderId: '1036782783280',
    projectId: 'yourvideocallvideo',
    storageBucket: 'yourvideocallvideo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkvAQY9M3Ab6isuXG0LpPkpZVCb5s0ms0',
    appId: '1:1036782783280:ios:d2f5402a478622445016f5',
    messagingSenderId: '1036782783280',
    projectId: 'yourvideocallvideo',
    storageBucket: 'yourvideocallvideo.firebasestorage.app',
    iosBundleId: 'com.example.videocallapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkvAQY9M3Ab6isuXG0LpPkpZVCb5s0ms0',
    appId: '1:1036782783280:ios:d2f5402a478622445016f5',
    messagingSenderId: '1036782783280',
    projectId: 'yourvideocallvideo',
    storageBucket: 'yourvideocallvideo.firebasestorage.app',
    iosBundleId: 'com.example.videocallapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV7gNrMOxcWkR_NlJGJq-GE5zOiXgo-rM',
    appId: '1:1036782783280:web:2b2e23532745e58b5016f5',
    messagingSenderId: '1036782783280',
    projectId: 'yourvideocallvideo',
    authDomain: 'yourvideocallvideo.firebaseapp.com',
    storageBucket: 'yourvideocallvideo.firebasestorage.app',
  );
}
